apiVersion: assignments.kube-valet.io/v1alpha1
kind: NodeAssignmentGroup
metadata:
  name: simple
spec:
  # Target all non-master nodes in the cluster
  targetLabels:
    node-role.kubernetes.io/worker: ""
  assignments:
    # Make sure one node has:
    #   label: nag.assignments.kube-valet.io/simple="true"
    - name: "true"
      numDesired: 1
