apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: kube-valet
initializers:
  - name: pod.initializer.kube-valet.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
