apiVersion: v1
kind: Pod
metadata:
  name: kube-valet
  namespace: kube-system
spec:
  serviceAccountName: kube-valet
  containers:
  - name: kube-valet
    # Production systems should use a stable version tag
    image: domoinc/kube-valet:latest
    imagePullPolicy: IfNotPresent
    command:
      - /kube-valet
      - --leader-elect
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
