# Match complex pods and apply all scheduling details to them
# this is overkill for most real workloads but shows what is possible
apiVersion: assignments.kube-valet.io/v1alpha1
kind: PodAssignmentRule
metadata:
  name: complex
spec:
  targetLabels:
    worktype: complex
  scheduling:
    mergeStrategy: OverwriteAll
    nodeSelector:
      worktype: complex
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/e2e-az-name
              operator: In
              values:
              - e2e-az1
              - e2e-az2
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: another-node-label-key
              operator: In
              values:
              - another-node-label-value
    tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule"
